name: "Auto Merge Authorized PRs"

on:
  workflow_run:
    workflows: ["Check Authorized Users"]
    types:
      - completed

jobs:
  approve-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Generate Installation Token"
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}

      - name: "Get PR Number"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_TARGET_REPO: ${{ github.repository }}
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
        run: |
          PR_NUMBER=$(gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
            --json number \
            --jq '.number')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR associated with this workflow run"
            exit 1
          fi
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          echo "PR number from workflow_run event: ${PR_NUMBER}"

      - name: "Approve PR"
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
        run: |
          gh pr review $PR_NUMBER --approve \
            --body "Changes approved. Thank you for your contribution."

      - name: "Merge PR"
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
        run: |
          gh pr merge --auto $PR_NUMBER --squash \
            --body "PR #${PR_NUMBER} was automatically merged because the user is authorized to modify these directories."
