name: "Check Authorized Users"

on:
  workflow_dispatch:
  pull_request_target:
    branches: main
    paths:
      - "model-output/**"
      - "!model-output/README.md"
      - "!model-output/CovidHub-ensemble/**"
      - "!model-output/CovidHub-baseline/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-authorization:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6

      - name: "Get All Changes"
        id: get_all_changed_files
        uses: step-security/changed-files@v47
        with:
          json: true

      - name: "Check Authorized Users"
        uses: cdcgov/hubhelpr/.github/actions/check-authorized-users@main
        with:
          changed_files: ${{ steps.get_all_changed_files.outputs.all_modified_files }}
          gh_actor: ${{ github.actor }}

      - name: "Upload Validation Status"
        uses: actions/upload-artifact@v6
        with:
          name: "validation_status"
          path: status
