name: "CovidHub-baseline"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * 3"

jobs:
  generate-baseline-forecasts:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: "Generate Installation Token"
      id: get_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: "Checkout Code"
      uses: actions/checkout@v6

    - name: "Setup R"
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: true
        use-public-rspm: true

    - name: "Set Up R Dependencies"
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        pak-version: "devel"
        packages: |
          github::cdcgov/hubhelpr

    - name: "Generate Baseline"
      run: Rscript -e "hubhelpr::generate_hub_baseline('.', forecasttools::ceiling_mmwr_epiweek(lubridate::today()), 'covid')"

    - name: "Set Date"
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: "Commit Changes"
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b add-covid-baseline-${{ env.DATE }}
        git add .
        git commit -m "Add CovidHub baseline forecasts"
        git push origin add-covid-baseline-${{ env.DATE }}

    - name: "Create Pull Request"
      id: create_pr
      run: |
        gh pr create --base main --head add-covid-baseline-${{ env.DATE }} --title "Add CovidHub baseline forecast" --body "This PR is generated automatically."
      env:
        GH_TOKEN: ${{ steps.get_token.outputs.token }}
