name: "CovidHub-baseline"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * 3"

jobs:
  generate-baseline-forecasts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
      
    - name: Install dependencies
      run: |
        install.packages(c("readr", "dplyr", "tidyr", "purrr", "checkmate", "cli", "lubridate", "remote"))
        remotes::install_github("cmu-delphi/epipredict")
  
    - name: generate baseline
      run: |
        Rscript src/code/get_baseline.R

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with: 
        message: "Add baseline forecasts"
        default_author: github_actions
        push: true
