name: "CovidHub-baseline"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * 3"

jobs:
  generate-baseline-forecasts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
      
    - name: Install dependencies
      run: |
        install.packages(c("readr", "dplyr", "tidyr", "purrr", "checkmate", "cli", "lubridate", "remotes", "genlasso"))
        remotes::install_github("cmu-delphi/epiprocess")
        remotes::install_github("cmu-delphi/epipredict")
      shell: Rscript {0}
  
    - name: generate baseline
      run: |
        TODAY=$(date +'%Y-%m-%d')
        REF_DATE=$(date -d "$TODAY + 3 days" +'%Y-%m-%d') 
        Rscript src/code/get_baseline.r --reference-date "$REF_DATE"

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with: 
        message: "Add baseline forecasts"
        default_author: github_actions
        push: true
        new_branch: add-baseline
  
    - name: Create pull request
      id: create_pr
      run: |
        gh pr create --base main --head add-baseline --title "Add baseline forecast" --body "This PR is generated automatically."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}