# The following is a workflow derived from
# https://github.com/posit-dev/setup-air/blob/main/examples/format-check.yaml
on:
  push:
    branches: [main, master]
  pull_request:

name: "Format Check"

permissions: read-all

jobs:
  format-check:
    name: "format-check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Install"
        uses: posit-dev/setup-air@v1

      - name: "Check"
        run: air format . --check
