name: "Update Authorized Users"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "model-metadata/*.yaml"
      - "model-metadata/*.yml"

jobs:
  update:
    if: ${{ github.repository_owner == 'CDCgov' }}
    uses: cdcgov/hubhelpr/.github/workflows/update-authorized-users.yaml@main
    with:
      github-app-id: ${{ vars.GH_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.GH_APP_KEY }}
