name: "Validate PRs"

on:
  workflow_dispatch:
  pull_request_target:
    branches: main
    paths:
      - "model-output/**"
      - "!model-output/README.md"
      - "!model-output/CovidHub-ensemble/**"
      - "!model-output/CovidHub-baseline/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate-and-save-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://hubverse-org.r-universe.dev"

      - name: "Set Up R Dependencies"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "devel"
          packages: |
            github::cdcgov/hubhelpr

      - name: "Get All Changes"
        id: get_all_changed_files
        uses: step-security/changed-files@v46
        with:
          json: true

      - name: "Check Changes for Auto-Approval"
        run: |
          changed_files <- jsonlite::fromJSON('${{ steps.get_all_changed_files.outputs.all_modified_files }}')
          hubhelpr::check_changes_for_autoapproval(
            changed_files = changed_files,
            gh_actor = "${{ github.actor }}",
            base_hub_path = "."
          )
        shell: Rscript {0}

      - name: "Save Validation Status"
        if: success()
        run: echo "success" > status

      - name: "Upload Validation Status"
        uses: actions/upload-artifact@v4
        with:
          name: "validation_status"
          path: status
